{% set name = "types-s3transfer" %}
{% set version = "0.6.0.post2" %}
{% set lib_version = version.split(".post")[0] %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-s3transfer-{{ version }}.tar.gz
  sha256: af5222a02eb1491828c01d3f7b0f77bc9600989ecfbff6df63a60b8ba88c4565

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - poetry
  commands:
    - pip check
    - python -c "import importlib; importlib.import_module('s3transfer-stubs')"

about:
  home: https://github.com/youtype/types-s3transfer
  summary: Type annotations for AWS s3transfer {{ lib_version }} library
  dev_url: https://github.com/youtype/types-s3transfer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vemel
